# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://ridhima30.github.io/
baseurl: /
title: Ridhima Bansal
author: Ridhima Bansal
description: Personal blog and resume
avatar: Ridhima.png
email: bansal.ridhima30@gmail.com
github: ridhima30 # username
twitter:
linkedin: ridhima-bansal14
stackoverflow:  #e.g: users/2735833/proton1h1
medium: #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
disqus:
google_analytics: G-M0D09V41H0

name: Ridhima Bansal
# email: bansal.ridhima30@gmail.com
email_full: mailto:bansal.ridhima30@gmail.com
website: github.io/ridhima30
website_full: ridhima30.github.io/
# github: ridhima30
# twitter:
tel: +91 (989) 9787404
tel_full: tel:++919899787404
google_maps: 'https://goo.gl/maps/fUApc7DLELDAdLah8'
address:
  street: New Delhi
  postcode: 110070
  city: Delhi
  country: India

# needed for travis-ci build
exclude: [vendor]
